version: '3'

vars:
  # Docker Compose
  COMPOSE_DIR: .docker/compose
  DBMATE_DIR: .db/migrations

silent: true

tasks:
  compose-stop:
    desc: Stops docker compose containers
    dir: "{{ .COMPOSE_DIR }}"
    cmds:
      - docker compose stop

  compose-run:
    desc: Runs docker compose
    dir: "{{ .COMPOSE_DIR }}"
    cmds:
      - docker compose up -d

  db-dump:
    desc: Dumps DB schema
    cmds:
      - dbmate -d {{ .DBMATE_DIR }} dump

  db-migrate:
    desc: Migrates DB schema
    cmds:
      - dbmate -d {{ .DBMATE_DIR }} up

  build:
    desc: Builds linux binary
    cmds:
      - env GOOS=linux GOARCH=amd64 go build -o anomaly cmd/app/*.go